// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faihlbsxbegfilcxfdry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaWhsYnN4YmVnZmlsY3hmZHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjc5ODcsImV4cCI6MjA2ODcwMzk4N30.NVcyfLnD2Z9bP4O6NBNYYy2pz50UqTI4TLyGe4UK94M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});